CREATE TABLE IF NOT EXISTS uShop (uShopCode NVARCHAR(6) PRIMARY KEY, uShopName NVARCHAR(20) NOT NULL);
CREATE TABLE IF NOT EXISTS uBuyIn (sBuyInCode NVARCHAR(12) PRIMARY KEY, uBuyDate TIMESTAMP NOT NULL, uShopCode NVARCHAR(6) NOT NULL, uNum INTEGER NOT NULL CHECK (uNum > 0), uMemo NVARCHAR(20));
CREATE TABLE IF NOT EXISTS uSellOut (sSellOutCode NVARCHAR(12) PRIMARY KEY, uSellDate TIMESTAMP NOT NULL, uShopCode NVARCHAR(6) NOT NULL, uNum INTEGER NOT NULL CHECK (uNum > 0), uMemo NVARCHAR(20));
CREATE TABLE IF NOT EXISTS uStorage (uShopCode NVARCHAR(6) PRIMARY KEY, uNum INTEGER NOT NULL);
INSERT INTO uShop(uShopCode,uShopName) SELECT 'SP0001','示例商品' WHERE NOT EXISTS (SELECT 1 FROM uShop WHERE uShopCode='SP0001');
